import { ChartData } from 'chart.js'

export const chartData = {
  labels: ['ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ', 'ВС'],
  padding: { left: 110 },
  datasets: [
    {
      borderRadius: 100,
      barThickness: 11,
      borderWidth: 2.5,
      borderColor: 'transparent',
      backgroundColor: '#9437F5',
      data: [
        {
          x: 0,
          y: 80,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 80,
          title: 'Отправил в AFK',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 80,
          title: 'Отправил в Проблемные',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 80,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 80,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 80,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 80,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
      ],
    },
    {
      borderRadius: 100,
      barThickness: 11,
      borderWidth: 2.5,
      borderColor: 'transparent',
      backgroundColor: '#279BE8',
      data: [
        {
          x: 0,
          y: 40,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 40,
          title: 'Отправил в AFK',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 40,
          title: 'Отправил в Проблемные',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 40,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 40,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 40,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 40,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
      ],
    },
    {
      borderRadius: 100,
      barThickness: 11,
      borderWidth: 2.5,
      borderColor: 'transparent',
      backgroundColor: '#FC9E24',
      data: [
        {
          x: 0,
          y: 160,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 260,
          title: 'Отправил в AFK',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 160,
          title: 'Отправил в Проблемные',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 260,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 160,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 260,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 160,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
      ],
    },
    {
      borderRadius: 100,
      barThickness: 11,
      borderWidth: 2.5,
      borderColor: 'transparent',
      backgroundColor: '#F52629',
      data: [
        {
          x: 0,
          y: 20,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 40,
          title: 'Отправил в AFK',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 20,
          title: 'Отправил в Проблемные',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 40,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 20,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 40,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 20,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
      ],
    },
    {
      borderRadius: 100,
      barThickness: 11,
      borderWidth: 2.5,
      borderColor: 'transparent',
      backgroundColor: '#CD765A',
      data: [
        {
          x: 0,
          y: 30,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 5,
          title: 'Отправил в AFK',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 30,
          title: 'Отправил в Проблемные',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 30,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 5,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 30,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 20,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
      ],
    },
    {
      borderRadius: 100,
      barThickness: 11,
      borderWidth: 2.5,
      borderColor: 'transparent',
      backgroundColor: '#667530',
      data: [
        {
          x: 0,
          y: 130,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 120,
          title: 'Отправил в AFK',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 130,
          title: 'Отправил в Проблемные',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 120,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 130,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 120,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 130,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
      ],
    },
    {
      borderRadius: 100,
      barThickness: 11,
      borderWidth: 2.5,
      borderColor: 'transparent',
      backgroundColor: '#F5D48B',
      data: [
        {
          x: 0,
          y: 105,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 105,
          title: 'Отправил в AFK',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 105,
          title: 'Отправил в Проблемные',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 105,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 105,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 105,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 105,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
      ],
    },
    {
      borderRadius: 100,
      barThickness: 11,
      borderWidth: 2.5,
      borderColor: 'transparent',
      backgroundColor: '#683CC3',
      data: [
        {
          x: 0,
          y: 105,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 130,
          title: 'Отправил в AFK',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 105,
          title: 'Отправил в Проблемные',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 130,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 105,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 130,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 105,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
      ],
    },
    {
      borderRadius: 100,
      barThickness: 11,
      borderWidth: 2.5,
      borderColor: 'transparent',
      backgroundColor: '#40EAE5',
      data: [
        {
          x: 0,
          y: 10,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 150,
          title: 'Отправил в AFK',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 10,
          title: 'Отправил в Проблемные',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 150,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 10,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 150,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 10,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
      ],
    },
    {
      borderRadius: 100,
      barThickness: 11,
      borderWidth: 2.5,
      borderColor: 'transparent',
      backgroundColor: '#11C471',
      data: [
        {
          x: 0,
          y: 30,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 20,
          title: 'Отправил в AFK',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 30,
          title: 'Отправил в Проблемные',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 20,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 30,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 20,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 30,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
      ],
    },
    {
      borderRadius: 100,
      barThickness: 11,
      borderWidth: 2.5,
      borderColor: 'transparent',
      backgroundColor: '#354E86',
      data: [
        {
          x: 0,
          y: 5,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 20,
          title: 'Отправил в AFK',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 5,
          title: 'Отправил в Проблемные',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 20,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 5,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 20,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
        {
          x: 0,
          y: 5,
          title: 'Overwatch 2',
          date: '22 июня 2023',
        },
      ],
    },
  ],
  color: '#fff',
} as ChartData
